services:
  web:
    image: nginx:alpine
    container_name: web_app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      custom_net:
        ipv4_address: 10.10.10.2
        aliases:
          - new_db
          - dev_db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      custom_net:
        ipv4_address: 10.10.10.3

volumes:
  db_data:

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28
