---
- name: Secure SSH user setup
  hosts: all
  become: true
  vars:
    username: devuser
    ssh_pub_key: "{{ lookup('file', 'id_ed25519.pub') }}"

  tasks:
    - name: Create a new user
      user:
        name: "{{ username }}"
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Create .ssh directory
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: Upload SSH public key
      copy:
        content: "{{ ssh_pub_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
        backrefs: yes

    - name: Ensure PubkeyAuthentication is enabled
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
        backrefs: yes

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted

    - name: Create a directory in /opt with 660 permissions
      file:
        path: "/opt/{{ username }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0660'
